COLUMNS = [
    "city",
    "city_id",
    "latitude",
    "longitude",
    "country",
    "timezone",
    "base",
    "weather_id",
    "weather_main",
    "weather_description",
    "weather_icon",
    "temperature",
    "feels_like",
    "temp_min",
    "temp_max",
    "pressure",
    "humidity",
    "sea_level",
    "ground_level",
    "visibility",
    "wind_speed",
    "wind_direction",
    "wind_gust",
    "rain_1h",
    "cloudiness",
    "observation_time",
    "sunrise",
    "sunset",
    "cod",
]

__all__ = ["COLUMNS"]